-- Mission Pack II: Underwatch Civic Action Protocols enum extensions

ALTER TYPE "MissionDifficulty" ADD VALUE 'SPECIALIST';

ALTER TYPE "MissionPackMissionType" ADD VALUE 'EVERYDAY_ACTIVISM';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'CIVIC_PARTICIPATION';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'CAMPAIGN_STRATEGY';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'WRITING_AND_MEDIA_LITERACY';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'VISUAL_ACTIVISM';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'DATA_LITERACY';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'COMMUNITY_SERVICE';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'ARCHIVING_AND_DOCUMENTATION_ETHICS';
ALTER TYPE "MissionPackMissionType" ADD VALUE 'NONVIOLENT_FIELD_PREPARATION';

ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_REFLECTION';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_CIVIC_LOG';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_PLANNING_SHEET';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'TEXT_LINK_AND_SOURCE_NOTES';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'ANONYMIZED_SUMMARY';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_SERVICE_LOG';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_ARCHIVE_PACKET';
ALTER TYPE "MissionSubmissionType" ADD VALUE 'REDACTED_SUPPORT_PLAN';
