import type { HadesTheme } from "./types";

const placeholderAssets = (themeId: string) => ({
  logo: `/assets/logo/${themeId}.svg`,
  favicon: `/assets/icons/${themeId}-favicon.svg`,
  backgroundImage: `/assets/backgrounds/${themeId}.webp`,
  backgroundVideo: `/assets/video/${themeId}-ambient.mp4`,
  textureOverlay: `/assets/textures/${themeId}-grain.png`,
  cursorImage: `/assets/icons/${themeId}-cursor.svg`,
  loadingAnimation: `/assets/video/${themeId}-loader.webm`,
  alertSound: `/assets/audio/${themeId}-alert.mp3`,
  loginAmbience: `/assets/audio/${themeId}-login-ambience.mp3`,
  dashboardAmbience: `/assets/audio/${themeId}-dashboard-ambience.mp3`,
});

export const themes: HadesTheme[] = [
  {
    id: "ghost-in-the-machine",
    name: "Ghost in the Machine",
    description:
      "Pale cyan signals bleeding through a drowned server room. Ethereal, haunted, and quietly hostile.",
    cssVariables: {
      background: "#0a0f14",
      foreground: "#d4f0ff",
      card: "#111a22",
      cardForeground: "#d4f0ff",
      primary: "#5ee7ff",
      primaryForeground: "#041018",
      secondary: "#1a2833",
      secondaryForeground: "#9edfff",
      muted: "#152028",
      mutedForeground: "#6a8f9f",
      accent: "#2a4a5a",
      accentForeground: "#b8ecff",
      destructive: "#ff4d6d",
      border: "#2a3d4d",
      ring: "#5ee7ff",
      glow: "#5ee7ff40",
    },
    overlays: { scanlines: true, glow: true, noise: true, vignette: true },
    assets: placeholderAssets("ghost-in-the-machine"),
  },
  {
    id: "terminal-kiddie",
    name: "Terminal Kiddie",
    description:
      "Neon green phosphor on cracked CRT glass. Raw packet dumps and midnight wardial energy.",
    cssVariables: {
      background: "#050a05",
      foreground: "#39ff14",
      card: "#0a140a",
      cardForeground: "#39ff14",
      primary: "#39ff14",
      primaryForeground: "#020502",
      secondary: "#0f1f0f",
      secondaryForeground: "#7fff5c",
      muted: "#0c180c",
      mutedForeground: "#2a8f1a",
      accent: "#1a3d12",
      accentForeground: "#7fff5c",
      destructive: "#ff3333",
      border: "#1a3d12",
      ring: "#39ff14",
      glow: "#39ff1430",
    },
    overlays: { scanlines: true, glow: false, noise: true, vignette: false },
    assets: placeholderAssets("terminal-kiddie"),
  },
  {
    id: "fallout-crt",
    name: "Fallout CRT",
    description:
      "Amber monochrome command terminals from a bunker that never received the all-clear.",
    cssVariables: {
      background: "#1a1208",
      foreground: "#ffb347",
      card: "#241a0c",
      cardForeground: "#ffb347",
      primary: "#ff8c00",
      primaryForeground: "#1a0f00",
      secondary: "#2e2210",
      secondaryForeground: "#ffcc80",
      muted: "#221a0a",
      mutedForeground: "#a07030",
      accent: "#3d2e14",
      accentForeground: "#ffcc80",
      destructive: "#cc3333",
      border: "#4a3820",
      ring: "#ff8c00",
      glow: "#ff8c0030",
    },
    overlays: { scanlines: true, glow: true, noise: true, vignette: true },
    assets: placeholderAssets("fallout-crt"),
  },
  {
    id: "neon-oracle",
    name: "Neon Oracle",
    description:
      "Violet prophecy circuits and hot magenta sigils. Divination through corrupted fiber optics.",
    cssVariables: {
      background: "#0d0518",
      foreground: "#f0e0ff",
      card: "#150a24",
      cardForeground: "#f0e0ff",
      primary: "#d946ef",
      primaryForeground: "#1a0520",
      secondary: "#1f0f35",
      secondaryForeground: "#e9b8ff",
      muted: "#180c28",
      mutedForeground: "#9a6ab8",
      accent: "#3d1a5c",
      accentForeground: "#f5c8ff",
      destructive: "#ff4466",
      border: "#3d2060",
      ring: "#d946ef",
      glow: "#d946ef40",
    },
    overlays: { scanlines: false, glow: true, noise: true, vignette: true },
    assets: placeholderAssets("neon-oracle"),
  },
  {
    id: "corporate-dystopia",
    name: "Corporate Dystopia",
    description:
      "Sterile cobalt compliance dashboards. Smile for the biometric audit, citizen.",
    cssVariables: {
      background: "#0a0e18",
      foreground: "#c8d4e8",
      card: "#101828",
      cardForeground: "#c8d4e8",
      primary: "#3b82f6",
      primaryForeground: "#050a14",
      secondary: "#182038",
      secondaryForeground: "#94b4e0",
      muted: "#141c30",
      mutedForeground: "#607090",
      accent: "#1e3050",
      accentForeground: "#a8c8f0",
      destructive: "#ef4444",
      border: "#243050",
      ring: "#3b82f6",
      glow: "#3b82f630",
    },
    overlays: { scanlines: false, glow: false, noise: false, vignette: true },
    assets: placeholderAssets("corporate-dystopia"),
  },
  {
    id: "underworld-ops",
    name: "Underworld Ops",
    description:
      "Blood-red tactical overlays on obsidian field consoles. Gothic command under eternal night.",
    cssVariables: {
      background: "#080608",
      foreground: "#e8d8d0",
      card: "#120e10",
      cardForeground: "#e8d8d0",
      primary: "#c41e3a",
      primaryForeground: "#1a0508",
      secondary: "#1e1418",
      secondaryForeground: "#d4a8a0",
      muted: "#161012",
      mutedForeground: "#806060",
      accent: "#2e1820",
      accentForeground: "#f0c0b8",
      destructive: "#ff2244",
      border: "#3a2028",
      ring: "#c41e3a",
      glow: "#c41e3a35",
    },
    overlays: { scanlines: true, glow: true, noise: true, vignette: true },
    assets: placeholderAssets("underworld-ops"),
  },
  {
    id: "null-signal",
    name: "Null Signal",
    description:
      "Void black with static white interference. The channel exists but transmits nothing.",
    cssVariables: {
      background: "#000000",
      foreground: "#e0e0e0",
      card: "#0a0a0a",
      cardForeground: "#e0e0e0",
      primary: "#ffffff",
      primaryForeground: "#000000",
      secondary: "#141414",
      secondaryForeground: "#b0b0b0",
      muted: "#101010",
      mutedForeground: "#606060",
      accent: "#1e1e1e",
      accentForeground: "#d0d0d0",
      destructive: "#ff0000",
      border: "#2a2a2a",
      ring: "#ffffff",
      glow: "#ffffff20",
    },
    overlays: { scanlines: true, glow: false, noise: true, vignette: true },
    assets: placeholderAssets("null-signal"),
  },
  {
    id: "arcade-necropolis",
    name: "Arcade Necropolis",
    description:
      "Electric cyan and hot pink on a dead arcade floor. High scores etched into tombstones.",
    cssVariables: {
      background: "#0a0818",
      foreground: "#f0f0ff",
      card: "#12102a",
      cardForeground: "#f0f0ff",
      primary: "#00f5ff",
      primaryForeground: "#020818",
      secondary: "#1a1840",
      secondaryForeground: "#ff6ec7",
      muted: "#141230",
      mutedForeground: "#7070a0",
      accent: "#2a2060",
      accentForeground: "#ff6ec7",
      destructive: "#ff3366",
      border: "#302860",
      ring: "#00f5ff",
      glow: "#00f5ff35",
    },
    overlays: { scanlines: true, glow: true, noise: false, vignette: false },
    assets: placeholderAssets("arcade-necropolis"),
  },
];

export const defaultThemeId = themes[0].id;

export function getThemeById(id: string): HadesTheme | undefined {
  return themes.find((t) => t.id === id);
}

export function getThemeOrDefault(id: string | null | undefined): HadesTheme {
  return getThemeById(id ?? "") ?? themes[0];
}
