import type { HubModuleDefinition, HubSectionDefinition } from "@/lib/mmo/hub-types";

export const HUB_TITLE = "FIELD OPS // UNDERWATCH COMMAND HUB";
export const HUB_SUBTITLE =
  "Your operative identity, faction work, community signals, and archive traces converge here.";

export const SAFETY_NOTICE =
  "Hades Watch progression rewards community support, creative work, privacy literacy, repair, archiving, mutual aid, safe ciphers, and nonviolent civic readiness. Do not submit secrets, private data, doxxing, harassment, unsafe tactics, or anything that could harm people.";

export const CHAT_WARNING =
  "HTTPS-protected temporary chat. No secrets. No archives.";

export const MISSION_SAFETY_NOTE =
  "Missions are safe, legal, nonviolent, and privacy-aware.";

const modules: HubModuleDefinition[] = [
  {
    slug: "character-dossier",
    title: "Character Dossier",
    eyebrow: "Character",
    description:
      "Your operative record. Callsign, avatar, badges, and traces of work completed under the Underwatch.",
    emptyState: "No operative dossier has stabilized yet.",
    route: "/profile",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Chthonic Uprising"],
    badgeHooks: ["callsign-claimed", "dossier-awakened"],
    loreHooks: ["mirror-chamber-online"],
    ctaLabel: "Open Dossier",
  },
  {
    slug: "avatar-builder",
    title: "Avatar Builder",
    eyebrow: "Character",
    description: "Forge your operative silhouette in the mirror chamber.",
    emptyState: "No avatar saved. The mirror is waiting for a signal.",
    route: "/profile/avatar",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Daedalus Foundry", "Styx Rats"],
    badgeHooks: ["mirror-chamber-initiate", "signal-wear-tailor"],
    loreHooks: ["mirror-chamber-online"],
    ctaLabel: "Enter Mirror Chamber",
  },
  {
    slug: "profile-world",
    title: "Profile World",
    eyebrow: "Character",
    description:
      "Your corner of the Underwatch wall. A dossier, shrine, signal, and strange little room.",
    emptyState: "No profile world has been lit yet.",
    route: "/profile",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Styx Rats", "Daedalus Foundry"],
    badgeHooks: ["profile-world-lit", "old-web-ghost"],
    loreHooks: [],
    ctaLabel: "View Profile World",
  },
  {
    slug: "relic-zone",
    title: "Relic Zone",
    eyebrow: "Character",
    description:
      "Customize a sandboxed relic zone without touching the wider dossier frame.",
    emptyState: "The relic zone is blank. Add a safe fragment of yourself.",
    route: "/profile/edit",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats", "Daedalus Foundry"],
    badgeHooks: ["relic-zone-spark", "sandbox-keeper"],
    loreHooks: [],
    ctaLabel: "Edit Relic Zone",
  },
  {
    slug: "badge-case",
    title: "Badge Case",
    eyebrow: "Character",
    description:
      "Marks earned through ciphers, missions, community work, and archive recovery.",
    emptyState: "No marks yet. Solve a cipher or complete a mission to begin.",
    route: "/profile",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Chthonic Uprising"],
    badgeHooks: ["badge-case-opened", "mark-bearer"],
    loreHooks: [],
    ctaLabel: "View Badges",
  },
  {
    slug: "faction-dossiers",
    title: "Faction Dossiers",
    eyebrow: "Factions",
    description:
      "Five Chthonic cells, one underworld signal. Choose where your work echoes.",
    emptyState: "No faction signal selected.",
    route: "/mmo/factions",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: [
      "Asclepian Veil",
      "Oracular Circuit",
      "Myrmidon Grinders",
      "Daedalus Foundry",
      "Styx Rats",
      "Chthonic Uprising",
    ],
    badgeHooks: ["dossier-reader", "faction-signal"],
    loreHooks: ["chthonic-cell-contact"],
    ctaLabel: "View Dossiers",
  },
  {
    slug: "mission-board",
    title: "Mission Board",
    eyebrow: "Missions",
    description:
      "Safe field orders for care, repair, privacy, documentation, civic readiness, and community resilience.",
    emptyState: "No active field orders. The Underwatch waits for your next signal.",
    route: "/mmo/missions",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Myrmidon Grinders", "Asclepian Veil"],
    badgeHooks: ["field-order-accepted", "first-descent"],
    loreHooks: ["first-descent-record"],
    ctaLabel: "View Field Orders",
    missionNote: MISSION_SAFETY_NOTE,
  },
  {
    slug: "active-missions",
    title: "Active Missions",
    eyebrow: "Missions",
    description:
      "Your open field orders, pending proof packets, and completed signal work.",
    emptyState: "No active field orders. Choose a mission to begin.",
    route: "/mmo/missions",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Myrmidon Grinders"],
    badgeHooks: ["thread-maintained", "proof-packet-filed"],
    loreHooks: [],
    ctaLabel: "Resume Field Log",
    missionNote: MISSION_SAFETY_NOTE,
  },
  {
    slug: "ciphers",
    title: "Ciphers",
    eyebrow: "Ciphers",
    description:
      "Crack Oracular transmissions, unlock Dead Index fragments, and earn the C1PH3R CR4K3R marks.",
    emptyState: "No active ciphers. The signal has gone quiet.",
    route: "/ciphers",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Oracular Circuit", "Dead Index"],
    badgeHooks: ["c1ph3r-cr4k3r-initiate", "dead-index-adept"],
    loreHooks: ["dead-index-first-trace"],
    ctaLabel: "Open Cipher Relay",
  },
  {
    slug: "community-builder",
    title: "Community Builder",
    eyebrow: "Community",
    description:
      "Plant a signal. Suggest a thread, resource, mission, banner, accessibility note, or lore fragment for Underwatch review.",
    emptyState: "No community signals queued. Plant the first one.",
    route: null,
    routeExists: false,
    status: "coming-soon",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats", "Daedalus Foundry", "Asclepian Veil"],
    badgeHooks: ["signal-planter", "commons-builder"],
    loreHooks: ["chthonic-commons"],
    ctaLabel: "Relay Locked",
    comingSoon: true,
  },
  {
    slug: "forums",
    title: "Forums / Conversation Threads",
    eyebrow: "Community",
    description:
      "Threaded old-web rooms for lore, mission debriefs, ciphers, tools, and community signals.",
    emptyState: "No threads in this channel. Start the first signal.",
    route: null,
    routeExists: false,
    status: "coming-soon",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats", "Oracular Circuit"],
    badgeHooks: ["first-thread", "signal-reply", "forum-steward"],
    loreHooks: ["forum-static-wakes"],
    ctaLabel: "Relay Locked",
    comingSoon: true,
  },
  {
    slug: "chat-rooms",
    title: "Chat Rooms",
    eyebrow: "Community",
    description:
      "Temporary signal rooms for approved operatives. Good for chatter, bad for secrets.",
    emptyState: "No static in this room yet.",
    route: "/chat",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats", "Oracular Circuit"],
    badgeHooks: ["static-whisper", "room-steward"],
    loreHooks: [],
    ctaLabel: "Enter Chat",
    chatWarning: CHAT_WARNING,
  },
  {
    slug: "net-neighbors",
    title: "Net Neighbors",
    eyebrow: "Community",
    description:
      "Small doors in the Underwatch wall. Follow at your own risk. Bring back anything beautiful, useful, strange, or kind.",
    emptyState: "No neighboring signals have cleared the Underwatch yet.",
    route: "/net-neighbors",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats", "Daedalus Foundry"],
    badgeHooks: ["net-neighbor-scout", "buttonmaker-ghost"],
    loreHooks: ["underwatch-wall-map"],
    ctaLabel: "Browse Neighbors",
  },
  {
    slug: "archive",
    title: "Archive",
    eyebrow: "Archive",
    description: "The Archive remembers what the surface buries.",
    emptyState: "No fragments recovered in this index yet.",
    route: "/archive",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Dead Index", "Chthonic Uprising"],
    badgeHooks: ["archive-reader", "lore-keeper"],
    loreHooks: ["archive-remembers"],
    ctaLabel: "Enter Archive",
  },
  {
    slug: "state-of-affairs",
    title: "State of Affairs",
    eyebrow: "Archive",
    description:
      "Public-interest signals, civic alerts, surveillance news, and digital-rights dispatches.",
    emptyState: "No surface dispatches have been indexed yet.",
    route: "/archive/state-of-affairs",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Oracular Circuit", "Myrmidon Grinders"],
    badgeHooks: ["dispatch-scout", "civic-signal"],
    loreHooks: [],
    ctaLabel: "Read Dispatches",
  },
  {
    slug: "ghost-in-tech",
    title: "Ghost in Tech",
    eyebrow: "Archive",
    description:
      "Repo relics, open-source tools, privacy projects, and useful code recovered from the surface web.",
    emptyState: "No repo relics have surfaced from the Ghost in Tech archive yet.",
    route: "/archive/ghost-in-tech",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Daedalus Foundry", "Oracular Circuit"],
    badgeHooks: ["repo-relic-reader", "ghost-in-tech-scout"],
    loreHooks: [],
    ctaLabel: "Browse Repos",
  },
  {
    slug: "lore-index",
    title: "Lore Index / Unlocks",
    eyebrow: "Archive",
    description: "Unlocked lore fragments, world memory, and Dead Index traces.",
    emptyState: "No lore fragments unlocked in this index yet.",
    route: "/archive/lore",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Dead Index"],
    badgeHooks: ["lore-keeper", "dead-index-trace"],
    loreHooks: [],
    ctaLabel: "Browse Lore",
  },
  {
    slug: "signal-player",
    title: "Signal Player",
    eyebrow: "Signals",
    description: "Tune the underworld frequency.",
    emptyState: "No signal loaded.",
    route: null,
    routeExists: false,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Styx Rats", "Chthonic Uprising"],
    badgeHooks: ["signal-listener", "underwatch-frequency"],
    loreHooks: [],
    ctaLabel: "Open Player",
  },
  {
    slug: "avatar-forge",
    title: "Avatar Forge",
    eyebrow: "Forge",
    description:
      "Forge your operative silhouette. Build compatible layers, relics, badges, and signal-wear for the Underwatch.",
    emptyState: "The forge relay is locked. Request access to begin.",
    route: "/profile/avatar/forge",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Daedalus Foundry", "Styx Rats"],
    badgeHooks: ["forge-door-knock", "asset-spark", "layerwright"],
    loreHooks: ["forge-door-knock"],
    ctaLabel: "Request Forge Access",
  },
  {
    slug: "avatar-prompt-reference",
    title: "Avatar Prompt Reference",
    eyebrow: "Forge",
    description: "Creator-facing prompt guidance for compatible operative layers.",
    route: null,
    routeExists: false,
    status: "coming-soon",
    accessLevel: "approved-user",
    factionAssociations: ["Daedalus Foundry"],
    badgeHooks: ["layerwright"],
    loreHooks: [],
    ctaLabel: "Docs Pending",
    comingSoon: true,
  },
  {
    slug: "banner-builder",
    title: "Net Neighbor Banner Builder",
    eyebrow: "Forge",
    description: "Build 88x31 banners for the Underwatch wall of small doors.",
    route: "/net-neighbors/submit",
    routeExists: true,
    status: "live",
    accessLevel: "approved-user",
    factionAssociations: ["Styx Rats"],
    badgeHooks: ["buttonmaker-ghost"],
    loreHooks: [],
    ctaLabel: "Submit Banner",
  },
  {
    slug: "volunteer-board",
    title: "Volunteer / Contributor Board",
    eyebrow: "Community",
    description:
      "Help build the underworld: docs, assets, accessibility, lore, tools, and strange useful systems.",
    emptyState: "No open calls posted. The Foundry is quiet for now.",
    route: null,
    routeExists: false,
    status: "coming-soon",
    accessLevel: "approved-user",
    factionAssociations: ["Daedalus Foundry", "Asclepian Veil"],
    badgeHooks: ["underwatch-volunteer", "commons-builder"],
    loreHooks: [],
    ctaLabel: "Relay Locked",
    comingSoon: true,
  },
  {
    slug: "events-transmissions",
    title: "Events / Transmissions",
    eyebrow: "Signals",
    description:
      "Current signals, seasonal transmissions, and time-bound Underwatch calls.",
    emptyState: "No active transmissions. Keep the receiver warm.",
    route: "/events",
    routeExists: true,
    status: "live",
    accessLevel: "logged-in",
    factionAssociations: ["Chthonic Uprising"],
    badgeHooks: ["transmission-received", "witness-mark"],
    loreHooks: [],
    ctaLabel: "View Transmissions",
  },
  {
    slug: "support",
    title: "Support the Underwatch",
    eyebrow: "Signals",
    description: "The future supply relay for keeping the Underwatch alive.",
    emptyState:
      "The Underwatch donation relay is not live yet. This placeholder marks where future support options will appear.",
    route: "/support",
    routeExists: true,
    status: "live",
    accessLevel: "public",
    factionAssociations: ["Chthonic Uprising"],
    badgeHooks: [],
    loreHooks: [],
    ctaLabel: "View Supply Relay",
  },
];

export const HUB_MODULES = modules;

export const HUB_MODULE_MAP = Object.fromEntries(
  modules.map((m) => [m.slug, m]),
) as Record<string, HubModuleDefinition>;

export const HUB_SECTIONS: HubSectionDefinition[] = [
  {
    id: "identity",
    title: "Identity / Character",
    subtitle: "Define who you are in the Underwatch.",
    moduleSlugs: [
      "character-dossier",
      "avatar-builder",
      "profile-world",
      "relic-zone",
      "badge-case",
    ],
  },
  {
    id: "field-work",
    title: "Field Work",
    subtitle: "Faction alignment, field orders, ciphers, and active signal work.",
    moduleSlugs: [
      "faction-dossiers",
      "mission-board",
      "active-missions",
      "ciphers",
    ],
  },
  {
    id: "community",
    title: "Community Signals",
    subtitle: "Forums, chat, Net Neighbors, and commons contributions.",
    moduleSlugs: [
      "community-builder",
      "forums",
      "chat-rooms",
      "net-neighbors",
      "volunteer-board",
    ],
  },
  {
    id: "archive",
    title: "Archive and Lore",
    subtitle: "The Archive remembers what the surface buries.",
    moduleSlugs: [
      "archive",
      "state-of-affairs",
      "ghost-in-tech",
      "lore-index",
    ],
  },
  {
    id: "forge",
    title: "Forge and Creator Tools",
    subtitle: "Build compatible layers, relics, badges, and signal-wear.",
    moduleSlugs: [
      "avatar-builder",
      "avatar-forge",
      "avatar-prompt-reference",
      "banner-builder",
    ],
  },
  {
    id: "signals",
    title: "Events / Transmissions",
    subtitle: "Current signals, player status, and supply relay.",
    moduleSlugs: ["signal-player", "events-transmissions", "support"],
  },
];

export function getHubModulesForSection(sectionId: string): HubModuleDefinition[] {
  const section = HUB_SECTIONS.find((s) => s.id === sectionId);
  if (!section) return [];
  return section.moduleSlugs
    .map((slug) => HUB_MODULE_MAP[slug])
    .filter(Boolean);
}
